- hosts: localhost
  become: true
  tasks:
  - name: Install packages
    apt:
    name: ['htop', 'vlc', 'geany', 'geany-plugins', 'galculator', 'ghex', 'okular', 'qtcreator', 'steam', 'calibre', 'claws-mail', 'hexchat', 'qbittorrent', 'wireshark', 'texstudio', 'mc', 'tmux']
