---
- hosts: localhost
  become: true
  pre_tasks:
  - name: Update repositories
    apt: update_cache=yes
    changed_when: False
    
  tasks:
  - include: tasks/remove_tor.yml
  - include: tasks/remove_galculator.yml
  - include: tasks/users.yml
  - include: tasks/cron.yml
  - include: tasks/packages.yml
    
