- name: Install packages
  apt: name={{items}}
  vars:
    items:
      - htop
      - vlc
      - geany
      - geany-plugins
      - gnome-calculator
      - ghex
      - okular
      - qtcreator
      - steam
      - calibre
      - claws-mail
      - hexchat
      - qbittorrent
      - wireshark
      - texstudio
      - python
      - python3
      - mc
      - tmux
      - passwordsafe
      - torbrowser-launcher
